//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeID { get; set; }
        public int StudentID { get; set; }
        public int CourseID { get; set; }
        public int LabGrade { get; set; }
        public int CourseGrade { get; set; }
        public Nullable<decimal> FinalGrade { get; set; }
        public Nullable<int> Credits { get; set; }
        public Nullable<decimal> CreditPoints { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual StudentCours StudentCours { get; set; }
        public virtual Student Student { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
